#!/usr/bin/env python3
"""
Generate paper/appendix_directions.tex: all 50 directions, every statistic the
paper reports for any of them, under all three nuisance models.

Added 2026-08-20. The workshop allows unlimited appendix pages, so there is no
reason for the main table to show 5 of 18 survivors and leave the rest unseen.

The table is GENERATED, never hand-edited: check_paper_consistency.py regenerates
it and asserts byte-equality with the committed file, so a stale or hand-tweaked
appendix fails the gate rather than shipping.

Analysis-only, reads existing JSON. Runtime <1 s.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "paper/appendix_directions.tex"


def render():
    J = json.load(open(ROOT / "results/paper_numbers.json"))
    C = json.load(open(ROOT / "results/conditional_null.json"))
    RB = json.load(open(ROOT / "results/robustness_controls.json"))
    surv = {m: set(RB[m]["survivors"])
            for m in ("baseline_length", "flexible_length", "task_fixed_effects")}
    beta = J["nested_lr"]["penalised"]
    resid = {d["direction"]: d["resid_auc"] for d in J["directions"]["all"]}
    dirs = sorted(C["chi2"], key=lambda e: -C["chi2"][e])

    L = []
    L.append(r"\section{All 50 directions}")
    L.append(r"\label{app:dirs}")
    L.append("")
    L.append(r"Table~\ref{tab:appdirs} is the full version of Table~\ref{tab:dirs}: every")
    L.append(r"direction, its log-likelihood improvement $T$ over a length-only model,")
    L.append(r"the family-wise max-$T$ $p$ under the conditional null, its Spearman correlation")
    L.append(r"with response length, its residualized AUC (below $0.5$ means a negative")
    L.append(r"association), and whether it clears $\alpha = .05$ under each of the three")
    L.append(r"nuisance models of \S\ref{sec:dirs}. Generated by")
    L.append(r"\texttt{scripts/make\_appendix\_table.py}; the consistency gate regenerates it")
    L.append(r"and requires byte-equality, so it cannot drift from the results it reports.")
    L.append("")
    L.append(r"\begin{table}[h]")
    L.append(r"\centering\scriptsize\setlength{\tabcolsep}{5pt}")
    L.append(r"\begin{tabular}{@{}lrrrrcc@{}}")
    L.append(r"\toprule")
    L.append(r"Direction & $T$ & max-$T$ $p$ & $\rho$(len) & resid.\ AUC"
             r" & +flex.\ len & +task \\")
    L.append(r"\midrule")
    # the survivors are the top of the chi2 ordering only if significance is monotone
    # in chi2 under this null; assert it rather than assume it before drawing the rule.
    cut = len(surv["baseline_length"])
    contiguous = set(dirs[:cut]) == surv["baseline_length"]
    for i, e in enumerate(dirs):
        if contiguous and i == cut:
            L.append(r"\midrule")
        f = r"$\checkmark$" if e in surv["flexible_length"] else "--"
        k = r"$\checkmark$" if e in surv["task_fixed_effects"] else "--"
        name = f"\\texttt{{{e}}}" + ("$^*$" if e == "desperate" else "")
        L.append(f"{name} & {C['chi2'][e]:.1f} & {C['p_conditional'][e]:.4f} & "
                 f"${RB['rho_length'][e]:+.2f}$ & {resid[e]:.3f} & {f} & {k} \\\\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\caption{All 50 directions, unsteered trials ($n = 120$, 14 events), ordered"
             r" by $T$. Rows above the second rule are the 18 that clear $\alpha = .05$"
             r" under the length-only nuisance model. The last two columns mark the 14 and 11"
             r" that also clear it under a cubic-plus-knots length basis and under task fixed"
             r" effects. $^*$Preregistered.}")
    L.append(r"\label{tab:appdirs}")
    L.append(r"\end{table}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)} ({len(render().splitlines())} lines)")
